---
title: "mixture expo"
author: "William R.P. Denault"
date: "2024-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  Mixture expo
Goal make a ebnm function for mixture of exponential using some of the script from ebnm
```{r cars}
library(ebnm)
set.seed(1)
n=4000
s <- rnorm(n, 1, 0.1)
x_true <-c(rexp(3000, rate = runif(3000,min=0.1)), rep(0, 1000)) 
x <- x_true + rnorm(n, sd = s)


par(mfrow=c(1,2))
plot(x_true)
plot(x)
par(mfrow=c(1,1))

true_pi0 <- 0.5
scale <- 1:10
true_mode <- 0

 g <- gammamix(pi = c(true_pi0,   rep(0.5/20,20)),
                   shape = c(1, rep(1,20)),
                   scale = c(0,  1:20),
                   shift = c(0, rep(0,20)))

 g
```


## Compute likelihood under Normal-Mix_expo

```{r }
mu=0 
 
 
  lf <- -0.5 * log(2  *pi* s^2) - 0.5 * (x - mu)^2 / s^2

# Exponential component:  
  a=  1/g$scale[-1]
  
  # <- matrix(rep(constant_value, num_rows * num_columns), nrow = num_rows, ncol = num_columns, byrow = TRUE)
  xright <-  ((x - mu) / s ) %*%t( rep(1, length(a)))  -  s %*%t( a)
  lpnormright <- pnorm(xright, log.p = TRUE)
  lg <- log( rep(1, length(x)) %*% t( a)) +  s^2%*%t( a^2) / 2 -  (x - mu)%*%t( a)    + lpnormright

mat_log_lik =  cbind(lf,lg)
 

```


finding a solution with mixsqp is somewhat straightforward


```{r}
library(mixsqp)

mixsqp_out <- mixsqp::mixsqp(mat_log_lik,
                            log=TRUE,
                            control = list(verbose=FALSE))
mixsqp_out$x# which seems to be about right
```


 

